# Generated by Django 4.2.5 on 2023-09-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="chat_memory_messages",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="moving_summary_buffer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="relationship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("In a relationship", "In a relationship"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Widowed", "Widowed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
