# Generated by Django 4.2.5 on 2023-09-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0003_alter_userprofile_chat_memory_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="moving_summary_buffer",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
