# Generated by Django 4.2.5 on 2023-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0005_alter_userprofile_chat_memory_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariofeedback",
            name="rating",
            field=models.IntegerField(default=1),
        ),
    ]
