# Generated by Django 4.2.5 on 2023-09-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0008_scenariofeedback_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="illness",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
